python -m sst2_finetune.qlora \
    --model_name_or_path ../models/bootlegged-llama2-7b-hf \
    --use_auth \
    --output_dir ./output/llama-2-guanaco-7b \
    --save_strategy steps \
    --data_seed 42 \
    --save_steps 500 \
    --save_total_limit 40 \
    --evaluation_strategy steps \
    --eval_dataset_size 1024 \
    --max_eval_samples 1000 \
    --per_device_eval_batch_size 32 \
    --max_new_tokens 32 \
    --dataloader_num_workers 1 \
    --group_by_length \
    --logging_strategy steps \
    --logging_steps 1 \
    --report_to wandb \
    --remove_unused_columns False \
    --do_train \
    --do_eval \
    --lora_r 32 \
    --lora_alpha 16 \
    --lora_modules all \
    --double_quant \
    --quant_type nf4 \
    --bits 4 \
    --fp16 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type constant \
    --gradient_checkpointing \
    --source_max_len 512 \
    --per_device_train_batch_size 32 \
    --gradient_accumulation_steps 1 \
    --max_steps 350 \
    --eval_steps 35 \
    --learning_rate 0.0002 \
    --adam_beta2 0.999 \
    --max_grad_norm 0.3 \
    --lora_dropout 0.1 \
    --weight_decay 0.0 \
    --seed 0 \
    --log_bytes_per_iteration \
    --log_bytes_total \
    # --debug underflow_overflow \
